### ISSUE TITLE
Monitoring epic, Oct 2017 … Sep 2018

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#226]
This ticket tracks enhancements to OONI infra monitoring through Oct 2017 … Sep 2018.

- [x] replace basic authentication in Prometheus with client SSL cert validation -- 23883a2104c1733b56c036c87ffc82754f60c6a3 & #155
- [x] configure cross-monitoring with another Prometheus -- 3bf09a7298666756ff73a213ad6d56658ed796e1
- [x] check that all inventory hosts are monitored -- d226bd144e0600cb441d1acdfb8ca2e0e91181e4
- [x] improve disk space alerts for filesystems over 50GiB -- 7c57b5bb16520bd6788bed1dc5af1731f6120042
- [x] monitor rare periodic jobs with push-gateway (e.g. `hellais-nas` backup) -- d6ba8fc4ef809fb49aace3308c1ae9ec5f0082c1
- [x] monitor IO stalls at GH, iowait% -- 085fd5a8e75018931c410eceed8f8b5171f0dec2
- [x] monitor IO stalls at GH, seeksample -- e342b1d50a7afb0857f93e057da811d2aff883f9
- [x] define "canonical" TSV log format for nginx -- edae501943e2c80fbd30ee4aaab3e5627a7b7ff0
- [x] monitor node_exporter/textfile liveness -- 7eff51c5781a0f4218560e6c008331bf47c6e19c
- [x] monitor nginx upstream request latency -- 6e65c46af2ec3f742e87b167566ee6fc5381d723
- [x] monitor airflow task failures -- 3f7cfac024bc8accbfcdcd314e8b952742215e75
- [x] speedup DiskWillFillInAWeek rule -- fd6318151df93df56a9e0553438113f99f6554c4
- [x] check that all GH host are stored in inventory -- 8a12b5ae9e4bd938e55653fed8911b9d8eb2be08
- [x] improve DiskWillFillInAWeek alerts -- 01daac85353440d61eb81b7494be0b8996e7e55b, b1b3995dcb435abfefb4922e3a659244c59abe83
- [x] monitor if OONI Website mirrors diverge -- f4841ef86af97cc4142275b41481cbc780cf3f45
- [x] deliver email alerts to MX (without smarthost) -- 2d220b23dcb7c7e07abd3e6103a8922a52d2fed4 #159
- [x] monitor CNAME shadowing other DNS resource records -- 24799886bcb1889dc0f1ab5dd8cd276ad3fb471d
- [x] monitor Slack-IRC gateway liveness -- b30e0d29d0512b8e1ce3cf1bd502388132c5af94
- [x] improve alerts on non-critical events -- 01bf91aa0da69a8c83fdf4c9e231d91145366b68, #158, #182
- [x] improve links in airflow alerts #153, #132
- [x] improve links in AlertManager alerts #128, #153, #132
- [x] ungroup AlertManager mails #211
- [x] monitor number of systemd services in failed state #220
- [x] investigate [dockerd monitoring](https://docs.docker.com/config/thirdparty/prometheus/) #220
- [x] investigate [running docker containers as systemd services](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/using_systemd_with_containers) #220
- [x] monitor anomalous and high CPU & NET usage, severity=info #135 #155
- [x] monitor memory pressure #211
- [x] monitor memory usage #101
- [x] monitor nodes with ICMP ping to distinguish stuck userspace from bad network #155
- [x] verify proper export of Disk IO stats #155
- [x] steal AlertManager health checks from gitlab #189

**Comment by darkk** [comment]
dockerd monitoring has at least one metric that sounds interesting: `engine_daemon_container_actions_seconds_count{action="start"}` that becomes rate of container restarts. Also, docker seems to implement backoff while restarting, so the restart loop is not "naive" busy loop.

**Comment by darkk** [comment]
> monitor number of systemd service restarts-per-minute

That's impossible with node_exporter 0.16.0 as soon as there are no metrics exported that can express that event. Seems, unreleased version of the node_exporter has alike features, but it's not in "stable" release yet. But frequent restarters are not "active" services so it's probably okay.

> monitor number of systemd services in failed state

node_systemd_units in node_exporter=0.16.0 shows that and also exports meta-self-test `is-system-running` as `node_systemd_system_running`.

Exporting systemd metrics should be done carefully as most of units are useless (`*.device`, `*.mount` and so on).

**Comment by darkk** [comment]
> investigate running docker containers as systemd services #220

Seems, it may be useful for graceful shutdown #172

**Comment by hellais** [comment]
> monitor number of systemd service restarts-per-minute

I also commented in #220, but posting it here too:

https://www.robustperception.io/alerting-on-crash-loops-with-prometheus

This does require that the to-be-monitored process uses some prometheus aware library. This is the case for gorush.

**Comment by SuperQ** [comment]
I'll be releasing a new node_exporter with the systemd restarts metric in the next week or so.

**Comment by darkk** [comment]
@hellais I would love to see it done in a more generic way as gorush is just a single service out of dozen. That's why I aimed for systemd & docker metrics.

**Comment by SuperQ** [comment]
@darkk IMO, directly instrumenting is extremely valuable. Even just adding the default Prometheus [client_golang](https://github.com/prometheus/client_golang) for example gives you a number of process metrics, including Go internals, process CPU, RSS, etc.

It also gives you the standard Prometheus `up` that can be used to discover down tasks.

**Comment by darkk** [comment]
> `node_systemd_system_running`

For some reason many hosts had no `dbus` package that is needed to access `systemd` from an unprivileged user (while all other systemd-enabled hosts had it!). I'm recording the list here for historical purposes:
- amsapi.ooni.nu
- amsdataproxy.ooni.nu
- amsmetadb.ooni.nu
- analytics.ooni.io
- get.ooni.io
- hkgcollectora.ooni.nu
- hkgjump.ooni.nu
- hkgmetadb.infra.ooni.io
- hkgwebconnectivitya.ooni.nu
- jupyter.ooni.io
- labs.ooni.io
- msg.ooni.io
- run.ooni.io
- shwdc.ooni.io
- ssdams.infra.ooni.io
- wiki.ooni.io
